import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
host = System.get_env("PHX_HOST") || "www.devjob-elixir.me"
gig_host = System.get_env("GIG_HOST") || "www.devjob-elixir.me"

config :dev_jobs, DevJobs.Mailer,
  adapter: Resend.Swoosh.Adapter,
  api_key: System.get_env("RESEND_API_KEY") || raise("RESEND_API_KEY is not set")

config :dev_jobs, DevJobsWeb.Endpoint,
  url: [host: "www.devjob-elixir.me", port: 443],
  check_origin: [host, gig_host],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: DevJobs.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
